---
# code: language=ansible
- name: Setup post create task
  hosts: all
  connection: local
  become: false
  vars:
    ## Base Directory
    ## -------------
    base_dir: "{{ ansible_facts.env.PWD | dirname | dirname }}"
    ## Development Tools
    ## -------------
    install_tools:
      - eza
      - osv-scanner
      - delta
      - lazygit
      - task
      - pict
      - glow
      - duckdb
      - gitleaks
      - github-cli
      - fnt
      ### 作図関連
      - d2
      - graphviz
      - plantuml
      - mermaid-cli
      - drawio
      ### ファイル変換
      - pandoc
      ### pdf関連
      - poppler-utils
      - diff-pdf
      ### node.js関連
      - zx
      - ni
      ### PHP関連
      - phpDocumentor
    ## Markitdown
    ## -------------
    markitdown_install: false
    markitdown_options:
      ### Installs dependencies for PowerPoint files
      - pptx
      ### Installs dependencies for Word files
      - docx
      ### Installs dependencies for Excel files
      - xlsx
      ###  Installs dependencies for older Excel files
      # - xls
      ### Installs dependencies for PDF files
      - pdf
      ### Installs dependencies for Outlook messages
      # - outlook
      ### Installs dependencies for Azure Document Intelligence
      # - az-doc-intel
      ### Installs dependencies for audio transcription of wav and mp3 files
      # - audio-transcription
      ### Installs dependencies for fetching YouTube video transcription
      # - youtube-transcription
  roles:
    - role: tools
      become: true
  tasks:
    - name: Install pip packages
      ansible.builtin.import_tasks:
        file: tasks/pip_package.yml
    - name: Set git setting
      ansible.builtin.import_tasks:
        file: tasks/git.yml
    - name: Set user environment setting
      ansible.builtin.import_tasks:
        file: tasks/environment.yml
    - name: Set bash-completion setting
      ansible.builtin.import_tasks:
        file: tasks/completion.yml
    - name: Find skeleton files
      ansible.builtin.find:
        paths:
          - skel
        hidden: true
        excludes:
          - .gitkeep
        recurse: true
      register: find_skeleton
    - name: Set skeleton file variable
      ansible.builtin.set_fact:
        skeleton_files: "{{ find_skeleton.files | map(attribute='path') }}"
    - name: Create directory
      ansible.builtin.file:
        path: "{{ base_dir }}/{{ dir_path }}"
        state: directory
        mode: "0755"
      loop: "{{ skeleton_files | map('dirname') | map('regex_replace', '^skel/?', '') | select() | unique }}"
      loop_control:
        loop_var: dir_path
        label: "{{ dir_path }}"
    - name: Copy skeleton files
      ansible.builtin.copy:
        src: "{{ skeleton_file }}"
        dest: "{{ base_dir }}/{{ skeleton_file | regex_replace('^skel/', '') }}"
        mode: "0644"
        remote_src: true
      loop: "{{ skeleton_files }}"
      loop_control:
        loop_var: skeleton_file
        label: "{{ skeleton_file | regex_replace('^skel/', '') }}"
