---
# code: language=ansible
- name: Setup post create task
  hosts: all
  connection: local
  become: false
  vars:
    base_dir: "{{ ansible_facts.env.PWD | dirname | dirname }}"
    install_tools:
      - osv-scanner
      - delta
      - lazygit
      - task
      - pict
      - duckdb
      - gitleaks
      - github-cli
      - fnt
      - d2
      # - graphviz
      # - plantuml
      - mermaid-cli
      - zx
      - ni
      - phpDocumentor
    github_cli_extensions:
      - github/gh-copilot
  roles:
    - role: tools
      become: true
  tasks:
    - name: Install pip packages
      ansible.builtin.import_tasks:
        file: tasks/pip_package.yml
    - name: Set git setting
      ansible.builtin.import_tasks:
        file: tasks/git.yml
    - name: Set user environment setting
      ansible.builtin.import_tasks:
        file: tasks/environment.yml
    - name: Set bash-completion setting
      ansible.builtin.import_tasks:
        file: tasks/completion.yml
    - name: Find skeleton files
      ansible.builtin.find:
        paths:
          - skel
        excludes:
          - .gitkeep
        recurse: true
      register: find_skeleton
    - name: Set skeleton file variable
      ansible.builtin.set_fact:
        skeleton_files: "{{ find_skeleton.files | map(attribute='path') }}"
    - name: Create directory
      ansible.builtin.file:
        path: "{{ base_dir }}/{{ dir_path }}"
        state: directory
        mode: "0755"
      loop: "{{ skeleton_files | map('dirname') | map('regex_replace', '^skel/', '') | unique }}"
      loop_control:
        loop_var: dir_path
        label: "{{ dir_path }}"
    - name: Copy skeleton files
      ansible.builtin.copy:
        src: "{{ skeleton_file }}"
        dest: "{{ base_dir }}/{{ skeleton_file | regex_replace('^skel/', '') }}"
        mode: "0644"
        remote_src: true
      loop: "{{ skeleton_files }}"
      loop_control:
        loop_var: skeleton_file
        label: "{{ skeleton_file | regex_replace('^skel/', '') }}"
